### ISSUE TITLE
Replace logos for state Senate and state House offices

### ISSUE THREAD

**Issue by DavidHerzog** [knowtheory/projectopenvault#29]
These are currently U.S. Senate and U.S. House. Replace with these.

Missouri Senate
http://www.senate.mo.gov/media/10info/Wright-Jones/Wright-JonesCapitolReport/2010/SenateSeal.jpg

Missouri House
http://www.house.mo.gov/graphics/mainimage.jpg

**Comment by crupar** [comment]
Sorry!  It's changed now.
